### PR TITLE
Bump rrweb version to 0.9.14

### PR DESCRIPTION
**Pull request by AlecDusheck**
I've tested rrweb 0.9.14 in a production environment with Sentry. Version 0.9.14 seems to be much more stable (still not all the way there) and throws less console errors.

### CODE REVIEW

**Comment by dcramer** [comment]
I would worry about forcing peer deps here. I think its fine for us to start building against it, but if we change peer deps we gotta make sure everyone can deal with it.

Any reason to not just keep the bare minimum?

**Comment by dcramer** [comment]
Counter argument to myself (sorry!): if we keep minimum we wont accurately test, so maybe just bumping minimum is the right call.

**Comment by AlecDusheck** [comment]
The reason why I bumped the peer dep was just because of how much rr-web changes under the hood. However, there aren't any _breaking_ changes in the rrweb api. Maybe its best to leave it as `>=0.7.0` and only bump when something breaks?

**Comment by dcramer** [comment]
My experience would tell me to only bump minimum when there's a breaking change (or maybe a security vuln). It isn't that big of a deal as we can do a version bump on sentry-rrweb to require the updating rrweb. So kind of open to either here. I havent been following the new features/improvements, so I will leave this back on your side if you think its worth it for users.

**Comment by bruno-garcia** [comment]
This repository has been superseded and will no longer be updated.

Please check https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#sentry-session-replay instead, we're happy to review and merge PRs there.

**Pull request closed without merging**
